language: node_js

sudo: false

cache:
  directories:
    - node_modules

node_js:
  - 7
  - 8

install:
  - npm install -g yarn lerna
  - yarn install

script:
  - yarn coveralls

notifications:
  email:
    on_success: never
    on_failure: change
