language: node_js

sudo: false

node_js:
  - 7
  - 8

install:
  - npm install -g yarn lerna
  - lerna bootstrap
  - yarn install

script:
  - yarn lint && yarn coveralls

notifications:
  email:
    on_success: never
    on_failure: change
