language: node_js

sudo: false

node_js:
  - 4.4
  - 5.0


install:
  - npm install

script:
  - npm test && npm run lint

after_success:
  - npm run coveralls

notifications:
  email:
    on_success: never
    on_failure: change
