language: node_js

sudo: false

cache:
  directories:
    - node_modules

node_js:
  - 7
  - 8

install:
  - npm install -g yarn lerna
  - lerna bootstrap
  - yarn install

script:
  - yarn coveralls

after_success:
  - npm install -g lerna-semantic-release
  - lerna-semantic-release pre
  - lerna-semantic-release perform
  - lerna-semantic-release post

notifications:
  email:
    on_success: never
    on_failure: change
